name: medics
description: A new Flutter project for UI design.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # state management getx
  get: ^4.6.6
  # store local storage
  shared_preferences: ^2.2.2
  # Flutter SVG
  flutter_svg: ^2.0.7
  # check internet connection
  connectivity_plus: ^5.0.1
  #introduction slider
  introduction_slider: ^2.0.1
  introduction_screen: ^3.1.12
#  readmore text
  readmore: ^3.0.0
#  rating bar
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  google_maps_flutter: ^2.6.1
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  zego_zimkit: ^1.18.7
  zego_uikit_prebuilt_call: ^4.12.2
  zego_uikit_signaling_plugin: ^2.7.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/images/
    - assets/data/
    - assets/data/doctor_data.json
    - assets/data/article_data.json
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

